language: cpp
sudo: require
dist: trusty

os:
 - linux
 - osx
matrix:
 exclude:
# Only do coverity or coverage build on Linux when the compiler is gcc
  - os: linux
    compiler: clang
    env: COVERITY=1
    env: COVERAGE=1
# Don't build with clang on Linux
  - os: linux
    compiler: clang
# Don't build with gcc on OSX
  - os: osx
    compiler: gcc

before_install: 
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y;
    sudo apt-get update -qq;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
    brew update > /dev/null;
    fi

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
    sudo apt-get -y install build-essential qt5-default qt510tools qt510base qt510quickcontrols2 g++-8 cmake libssl-dev doxygen zlib1g-dev;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
    brew install qt5;
    brew install zlib;
    brew install openssl;
    chmod -R 755 /usr/local/opt/qt5/*;
    fi

script: 

- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    source /opt/qt*/bin/qt*-env.sh;
    cmake -DEnableOpenSSL=ON -DBuildWidgetGallery=ON -DBuildQmlGallery=ON -DBuildDocs=ON CMakeLists.txt;
    make -j2;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    export QTDIR="/usr/local/opt/qt5";
    export PATH="/usr/local/opt/openssl/bin:$PATH";
    export PATH="$QTDIR/bin:$PATH";
    export LIBRARY_PATH=/usr/local/opt/openssl/lib;
    cmake -DEnableOpenSSL=ON -DBuildWidgetGallery=ON -DBuildQmlGallery=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl CMakeLists.txt;
    fi

deploy:
  provider: pages
  local-dir: docs/doc/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    os: linux
    branch: master

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "eqXxhT2R/eCXwaQC0dn14iB6Rvd7KdEsz9lvcqo/ZCSduHVdQbIcLKxI/gLXjYyPOurAgMDGlbiqe/Sz/29eH+jcYlNsLtDpSoJFsgnWe9KlEqBrbO+eGH5OoAabgJthcGygTwbFnpsiY7SvLG62pSYUrSfToCVkouSiUXeZb5Q="

addons:
  coverity_scan:
    project:
      name: "sithlord48/ff7tk"
      description: "Build submitted via Travis CI"
    notification_email: sithlord48@gmail.com
    build_command_prepend: "qmake ../ff7tkWidgetGallery/ff7tkWidgetGallery.pro"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
