language: cpp
dist: xenial
osx_image: xcode10.3

os:
 - linux
 - osx
jobs:
 exclude:
# Don't build with clang on Linux
  - os: linux
    compiler: clang
# Don't build with gcc on OSX
  - os: osx
    compiler: gcc

before_install: 
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-xenial -y;
    sudo apt-get update -qq;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
    brew update > /dev/null;
    brew cleanup;
    fi

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt-get -y install build-essential qt5-default qt515tools qt515base qt515quickcontrols2 g++-8 zsync doxygen;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew install qt@5;
    brew install doxygen;
    brew upgrade cmake;
    chmod -R 755 /usr/local/opt/qt5/*;
    fi

script:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    source /opt/qt*/bin/qt*-env.sh;
    cmake -DWIDGET_GALLERY=ON -DQML_GALLERY=ON -DDOCS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr CMakeLists.txt;
    make -j4;
    make DESTDIR=ff7tk-continuous-linux install;
    mkdir ff7tk;
    sudo cp -r ff7tk-continuous-linux/usr /;
    cp -r ff7tk-continuous-linux/usr ff7tk;
    rm -rf ff7tk/usr/bin;
    rm -rf ff7tk/usr/share/applications;
    rm -rf ff7tk/usr/share/pixmaps;
    rm -rf ff7tk-continuous-linux/usr/share/doc;
    rm -rf ff7tk-continuous-linux/usr/share/ff7tk;
    rm -rf ff7tk-continuous-linux/usr/share/pkgconfig;
    rm -rf ff7tk-continuous-linux/usr/include;
    rm -rf ff7tk-continuous-linux/lib/x86_64-linux-gnu;
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    mkdir widgetGallery;
    cp -r ff7tk-continuous-linux/usr widgetGallery;
    unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH;
    rm widgetGallery/usr/bin/ff7tkQmlGallery;
    rm widgetGallery/usr/share/applications/ff7tkQmlGallery.desktop;
    rm widgetGallery/usr/share/pixmaps/ff7tkQmlGallery.png;
    cp /usr/lib/x86_64-linux-gnu/libz.so widgetGallery/usr/lib/;
    ./linuxdeployqt*.AppImage widgetGallery/usr/share/applications/*.desktop -appimage;
    mkdir qmlGallery;
    cp -r ff7tk-continuous-linux/usr qmlGallery;
    rm qmlGallery/usr/bin/ff7tkWidgetGallery;
    rm qmlGallery/usr/share/applications/ff7tkWidgetGallery.desktop;
    rm qmlGallery/usr/share/pixmaps/ff7tkWidgetGallery.png;
    ./linuxdeployqt*.AppImage ./qmlGallery/usr/share/applications/*.desktop -bundle-non-qt-libs;
    cp /usr/lib/x86_64-linux-gnu/libz.so qmlGallery/usr/lib/;
    mkdir -p qmlGallery/usr/qml/QtQuick;
    cp -r /opt/qt515/qml/QtQuick/Controls.2 qmlGallery/usr/qml/QtQuick;
    cp -r /opt/qt515/qml/QtQuick/Layouts qmlGallery/usr/qml/QtQuick;
    cp -r /opt/qt515/qml/QtQuick/Window.2 qmlGallery/usr/qml/QtQuick;
    cp -r /opt/qt515/qml/QtQuick/Templates.2 qmlGallery/usr/qml/QtQuick;
    cp -r /opt/qt515/qml/QtQuick.2/ qmlGallery/usr/qml/;
    ./linuxdeployqt*.AppImage ./qmlGallery/usr/share/applications/*.desktop -appimage;
    mv ff7tk*.AppImage ff7tk-continuous-linux/;
    mv ff7tk/ ff7tk-continuous-linux;
    mv COPYING.TXT ff7tk-continuous-linux/;
    rm -rf ff7tk-continuous-linux/usr;
    tar -zcvf ff7tk-continuous-linux.tar.gz ff7tk-continuous-linux/;
    fi

- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    export QTDIR="/usr/local/opt/qt5";
    export PATH="$QTDIR/bin:$PATH";
    cmake -DWIDGET_GALLERY=ON -DQML_GALLERY=ON -DDOCS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr CMakeLists.txt;
    make -j4;
    make DESTDIR=ff7tk-continuous-macos install;
    mv COPYING.TXT ff7tk-continuous-macos/;
    mkdir ff7tk;
    cp -r ff7tk-continuous-macos/usr ff7tk;
    rm -rf ff7tk/usr/bin;
    mv ff7tk/ ff7tk-continuous-macos;
    mv ff7tk-continuous-macos/usr/bin/ff7tk*.app ff7tk-continuous-macos/;
    rm -rf ff7tk-continuous-macos/usr;
    cp ff7tk-continuous-macos/ff7tk/usr/lib/libff7tk.0.dylib ff7tk-continuous-macos/ff7tkWidgetGallery.app/Contents/MacOS;
    cp ff7tk-continuous-macos/ff7tk/usr/lib/libff7tkFormats.0.dylib ff7tk-continuous-macos/ff7tkWidgetGallery.app/Contents/MacOS;
    cp ff7tk-continuous-macos/ff7tk/usr/lib/libff7tkUtils.0.dylib ff7tk-continuous-macos/ff7tkWidgetGallery.app/Contents/MacOS;
    cp ff7tk-continuous-macos/ff7tk/usr/lib/libff7tkWidgets.0.dylib ff7tk-continuous-macos/ff7tkWidgetGallery.app/Contents/MacOS;
    macdeployqt ff7tk-continuous-macos/ff7tkWidgetGallery.app;
    install_name_tool -change @rpath/libff7tk.0.dylib @executable_path/libff7tk.0.dylib ff7tk-continuous-macos/ff7tkWidgetGallery.app/Contents/MacOS/ff7tkWidgetGallery;
    install_name_tool -change @rpath/libff7tkFormats.0.dylib @executable_path/libff7tkFormats.0.dylib ff7tk-continuous-macos/ff7tkWidgetGallery.app/Contents/MacOS/ff7tkWidgetGallery;
    install_name_tool -change @rpath/libff7tkUtils.0.dylib @executable_path/libff7tkUtils.0.dylib ff7tk-continuous-macos/ff7tkWidgetGallery.app/Contents/MacOS/ff7tkWidgetGallery;
    install_name_tool -change @rpath/libff7tkWidgets.0.dylib @executable_path/libff7tkWidgets.0.dylib ff7tk-continuous-macos/ff7tkWidgetGallery.app/Contents/MacOS/ff7tkWidgetGallery;
    cp ff7tk-continuous-macos/ff7tk/usr/lib/libff7tk.0.dylib ff7tk-continuous-macos/ff7tkQmlGallery.app/Contents/MacOS;
    macdeployqt ff7tk-continuous-macos/ff7tkQmlGallery.app;
    install_name_tool -change @rpath/libff7tk.0.dylib @executable_path/libff7tk.0.dylib ff7tk-continuous-macos/ff7tkQmlGallery.app/Contents/MacOS/ff7tkQmlGallery;
    mkdir -p ff7tk-continuous-macos/ff7tkQmlGallery.app/Contents/Resources/qml/QtQuick/Layouts;
    cp -r $QTDIR/qml/QtQuick/Layouts ff7tk-continuous-macos/ff7tkQmlGallery.app/Contents/Resources/qml/QtQuick/;
    mkdir -p ff7tk-continuous-macos/ff7tkQmlGallery.app/Contents/Resources/qml/QtQuick/Controls;
    cp -r $QTDIR/qml/QtQuick/Controls ff7tk-continuous-macos/ff7tkQmlGallery.app/Contents/Resources/qml/QtQuick/;
    zip -r -X ff7tk-continuous-macos.zip ff7tk-continuous-macos;
    fi
before_deploy:
  - git config --local user.name "sithlord48"
  - git config --local user.email "sithlord48@gmail.com"
  - git tag -f continuous
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/doc/html
    token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      condition: ${TRAVIS_OS_NAME} = linux
      branch: master
  - provider: releases
    edge: true
    cleanup: false
    token: $GITHUB_TOKEN
    tag_name: continuous
    target_commitish: $TRAVIS_COMMIT
    overwrite: true
    file_glob: true
    file: ff7tk-continuous-*.*
    on:
      branch: master
      tags: true

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:gh-pages)$/
