name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  Qt_Tools: tools_ifw
  QT_VERSION: 6.2.3

jobs:
  main_build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      BUILD_TYPE: RelWithDebInfo
      Qt_Tools: tools_ifw
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
           name: "Linux-amd64"
           , os: ubuntu-20.04
           , QT_INST_DIR: /opt
           , packageName: ff7tk-continuous-linux
           , ff7tkInstallPrefix: /usr
          }
        - {
            name: "MacOS-amd64"
            , os: macos-10.15
            , QT_INST_DIR: /Users/runner
          }
        - {
            name: "Windows-x64"
            , os: windows-2019
            , QT_INST_DIR: "C:"
            , extraCmakeConfig: "-DZLIB_ROOT=C:/zlib -G Ninja"
            , packageName: ff7tk-continuous-win64
            , ff7tkInstallPrefix: ff7tk-continuous-win64
          }

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{matrix.config.QT_INST_DIR}}/Qt
        key: ${{ runner.os }}${{ matrix.config.WIN_ARCH }}-qt-${{ matrix.config.QT_VERSION }}-${{ env.Qt_Tools }}

    - name: Cache Zlib
      id: cache-zlib
      if: runner.os == 'Windows'
      uses: actions/cache@v2
      with:
        path: |
          C:/zlib
          D:/a/ff7tk/ff7tk/build/src/utils/zlib.dll
        key: ${{ runner.os }}${{ matrix.config.WIN_ARCH }}-zlib2

    - name: Cache Chocolatey
      id: cache-choco
      if: (runner.os == 'Windows')
      uses: actions/cache@v2
      with:
        path: |
            C:\ProgramData\chocolatey\lib
            C:\Program Files\doxygen
            C:\Program Files\Graphviz
        key: cache-chocolatey-${{ matrix.config.WIN_ARCH }}${{ hashFiles('**/dependencies.config') }}

    - name: Env Script (Windows)
      uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'

    - name: Install Dependencies
      if: ((runner.os == 'Windows') && (steps.cache-choco.outputs.cache-hit != 'true')) || (runner.os != 'Windows')
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update > /dev/null && sudo apt-get install -qqq doxygen graphviz devscripts > /dev/null
        elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install ninja doxygen.install graphviz --ignore-checksums
        else
            brew install doxygen graphviz
        fi

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
       aqtversion: ==2.0.0
       py7zrversion: ==0.16.2
       dir: ${{matrix.config.QT_INST_DIR}}
       version: ${{ env.QT_VERSION }}
       modules: qt5compat
       cached: ${{ steps.cache-qt.outputs.cache-hit }}
       tools: 'desktop,tools_ifw,qt.tools.ifw.42'

    - name: Install Zlib (Windows)
      if: (runner.os == 'Windows') && (steps.cache-zlib.outputs.cache-hit != 'true')
      run: |
        git clone -q --branch=v1.2.11 https://github.com/madler/zlib ${{github.workspace}}\zlib-git
        cmake -S${{github.workspace}}\zlib-git -B${{github.workspace}}\zlib-git\build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=C:/zlib
        cmake --build ${{github.workspace}}\zlib-git\build --config ${{env.BUILD_TYPE}}
        cmake --install ${{github.workspace}}\zlib-git\build --strip
        mkdir D:\a\ff7tk\ff7tk\build\src\utils
        copy "C:\zlib\bin\zlib.dll" D:\a\ff7tk\ff7tk\build\src\utils

    - name: Build ff7tk
      id: main_build
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_DEMOS=ON -DCPACK_PACKAGE_VERSION=continuous -DQT_DEFAULT_MAJOR_VERSION=6 ${{matrix.config.extraCmakeConfig}}
        cmake --build build --config ${{env.BUILD_TYPE}} --target package

    - name: Deployment (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p ${{matrix.config.packageName}}/usr ff7tk
        tar -xf build/ff7tk-*.tar.gz -C ${{matrix.config.packageName}}/usr
        cp -r ${{matrix.config.packageName}}/* ff7tk/
        rm -rf ff7tk/usr/bin
        wget -qc "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
        wget -qc "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"
        chmod a+x linuxdeploy*.AppImage
        rm -rf ff7tk/usr/share/applications ff7tk/usr/share/pixmaps
        export VERSION=continuous
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{matrix.config.packageName}}/usr/lib
        export PATH=$PATH:${{matrix.config.QT_INST_DIR}}/Qt/${{ env.QT_VERSION }}/gcc_64/libexec
        ${{matrix.config.linuxDeployQtPath}}
        ./linuxdeploy-x86_64.AppImage --appdir=widgetGallery --plugin=qt --output appimage \
            -e ${{matrix.config.packageName}}/usr/bin/ff7tkWidgetGallery \
            -d ${{matrix.config.packageName}}/usr/share/applications/ff7tkWidgetGallery.desktop \
            -i ${{matrix.config.packageName}}/usr/share/pixmaps/ff7tkWidgetGallery.png
        export QML_SOURCES_PATHS=demos/ff7tkQmlGallery
        ./linuxdeploy-x86_64.AppImage --appdir=qmlGallery --plugin=qt --output appimage \
            -e ${{matrix.config.packageName}}/usr/bin/ff7tkQmlGallery \
            -d ${{matrix.config.packageName}}/usr/share/applications/ff7tkQmlGallery.desktop \
            -i ${{matrix.config.packageName}}/usr/share/pixmaps/ff7tkQmlGallery.png
        mv ff7tk*.AppImage ${{matrix.config.packageName}}/
        mv ff7tk/usr/COPYING.TXT ${{matrix.config.packageName}}/
        mv ff7tk/ ${{matrix.config.packageName}}
        rm -rf ${{matrix.config.packageName}}/usr
        tar -zcvf build/${{ matrix.config.packageName}}.tar.xz ${{matrix.config.packageName}}

    - name: Deploy Pages
      if: runner.os == 'Linux' && github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
       branch: gh-pages
       folder: build/docs/html

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/build/ff7tk[-_]*.*

  container_build:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: ${{matrix.config.name}}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
           name: "Linux-aarch64"
           , arch: aarch64, distro: archarm_latest
          }
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.config.arch }}
          distro: ${{ matrix.config.distro }}
          githubToken: ${{ github.token }}
          setup: mkdir -p "${PWD}/artifacts"
          dockerRunArgs: --volume "${PWD}/artifacts:/artifacts"
          shell: /bin/sh
          install: |
                pacman -Syu --noconfirm
                pacman -S base-devel cmake git zlib wget doxygen qt6-tools qt6-base qt6-5compat qt6-declarative qt6-svg clang graphviz --noconfirm

          run: |
            cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_DEMOS=ON -DCPACK_PACKAGE_VERSION=continuous -DQT_DEFAULT_MAJOR_VERSION=6 ${{matrix.config.cmakeExtraConfig}}
            cmake --build build --config RelWithDebInfo --target package
            mv build/ff7tk* /artifacts/
            rm /artifacts/ff7tk.pc

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ff7tk-container-artifact
          path: artifacts/ff7tk[-_]*.*

  release_assets:
    name: Release
    needs: [main_build, container_build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Download Files
      uses: actions/download-artifact@v2

    - name: Deploy Package
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
       repo_token: "${{ secrets.DEPLOYTOKEN }}"
       automatic_release_tag: "continuous"
       prerelease: false
       title: "Continuous Build"
       files: |
         artifact/*
         ff7tk-container-artifact/*
